services:
  - type: web
    name: findmate-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_NAME
        value: FindMate
      - key: CORS_ORIGINS
        sync: false
      - key: MONGO_URL
        sync: false
