import { useEffect, useMemo, useState } from "react";
import { profiles } from "../data/teamData";
import { profileApi, resumeApi, teamApi } from "../services/api";
import {
  generateSmartTeams,
  getAnalytics,
  normalizeMember,
} from "../utils/teamEngine";
import { TeamContext } from "./teamContextObject";

const initialMembers = profiles.map(normalizeMember);

import { mergeMembers } from "../utils/apiNormalizers";



export function TeamProvider({ children }) {
  const [members, setMembers] = useState(initialMembers);
  const [teams, setTeams] = useState(() => generateSmartTeams(initialMembers));
  const [teamRuns, setTeamRuns] = useState([]);
  const [resumeAnalyses, setResumeAnalyses] = useState([]);
  const [activity, setActivity] = useState([
    "Seed team workspace created",
    "Initial smart teams generated",
  ]);
  const [loading, setLoading] = useState({
    profiles: false,
    resume: false,
    teams: false,
  });

  const updateLoading = (key, value) => {
    setLoading((prev) => ({ ...prev, [key]: value }));
  };

  const addActivity = (message) => {
    setActivity((current) => [message, ...current].slice(0, 8));
  };

  useEffect(() => {
    let ignore = false;

    const loadPersistedProfiles = async () => {
      updateLoading("profiles", true);

      try {
        const savedProfiles = await profileApi.list();
        if (ignore || !savedProfiles.length) return;

        const restoredMembers = mergeMembers(initialMembers, savedProfiles);
        setMembers(restoredMembers);

        try {
          const runs = await teamApi.getRuns();
          if (!ignore) {
            setTeamRuns(runs);
            if (runs.length > 0) {
              setTeams(runs[0].teams);
              addActivity(`${savedProfiles.length} profiles and latest team run loaded from backend`);
            } else {
              setTeams(generateSmartTeams(restoredMembers));
              addActivity(`${savedProfiles.length} saved profiles loaded from backend`);
            }
          }
        } catch {
          if (!ignore) {
            setTeams(generateSmartTeams(restoredMembers));
            addActivity(`${savedProfiles.length} saved profiles loaded from backend`);
          }
        }
      } catch {
        if (!ignore) {
          addActivity("Backend unavailable, using seed workspace");
        }
      } finally {
        if (!ignore) {
          updateLoading("profiles", false);
        }
      }
    };

    loadPersistedProfiles();

    return () => {
      ignore = true;
    };
  }, []);

  const addMember = async (member) => {
    const normalized = normalizeMember(member);
    setMembers((current) => mergeMembers(current, [normalized]));
    addActivity(`${normalized.name} added as ${normalized.role}`);

    try {
      await profileApi.create(normalized);
    } catch {
      addActivity("Backend unavailable, member stored in current session");
    }

    return normalized;
  };

  const removeMember = async (id) => {
    setMembers((current) => current.filter((m) => m.id !== id));
    addActivity("Member removed from roster");

    try {
      await profileApi.delete(id);
    } catch {
      addActivity("Backend unavailable, member removed only in current session");
    }
  };

  const analyzeResume = async (file) => {
    updateLoading("resume", true);

    try {
      const result = await resumeApi.analyze(file);
      setResumeAnalyses((current) => [result, ...current]);
      addActivity(`Resume analyzed: ${result.recommended_role || "role recommended"}`);
      return result;
    } catch {
      const fallback = {
        detected_skills: ["React", "Python", "FastAPI"],
        recommended_role: "Full Stack Developer",
        confidence: 0.72,
        note: "Local fallback used because the backend is not reachable.",
      };

      setResumeAnalyses((current) => [fallback, ...current]);
      addActivity("Resume analysis used local fallback");
      return fallback;
    } finally {
      updateLoading("resume", false);
    }
  };

  const generateTeams = async () => {
    updateLoading("teams", true);

    try {
      const nextTeams = await teamApi.generate(members);
      setTeams(nextTeams);

      try {
        const runs = await teamApi.getRuns();
        setTeamRuns(runs);
      } catch {
        // ignore
      }

      addActivity(`${nextTeams.length} balanced teams generated by API`);
      return nextTeams;
    } catch {
      const nextTeams = generateSmartTeams(members);
      setTeams(nextTeams);
      addActivity("Backend unavailable, local team engine generated teams");
      return nextTeams;
    } finally {
      updateLoading("teams", false);
    }
  };

  const analytics = useMemo(() => getAnalytics(members, teams), [members, teams]);

  const value = {
    members,
    teams,
    teamRuns,
    analytics,
    resumeAnalyses,
    activity,
    loading,
    addMember,
    removeMember,
    analyzeResume,
    generateTeams,
  };

  return <TeamContext.Provider value={value}>{children}</TeamContext.Provider>;
}
